language: csharp
solution: src/OpenWheels.sln
dotnet: 2.1.2
mono: none
script: dotnet pack -c Release src/OpenWheels.sln
after_success: dotnet nuget push bin/Release/*.nupkg -s https://www.myget.org/F/jjagg -k $MYGET_JJAG_API_KEY 

